# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FastlaneTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FastlaneTest

  target 'FastlaneTestTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire'
  end

end
